config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'users/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', {to: 'home#index', as: 'root'}
  get '/about', {to: 'home#about'}
  get '/my_favourites', {to: 'home#favourites', as: 'my_favourites'}

  resources :projects

  resources :projects do
    resources :tasks
    resources :discussions
  end

  resources :discussions do
    resources :comments
  end

  patch '/projects/:project_id/tasks/:id/complete', {to: 'tasks#complete', as: 'task_complete'}

  resources :users, only: [:new, :create, :edit, :update]
  get '/users/:id/edit_password', {to:"users#edit_password", as: :edit_user_password}
  # patch '/users/:id/update_password', {to: 'users#update_password', as: :user_password}
  resource :sessions, only: [:new, :create, :destroy]

  resources :projects do
    resources :favourites, only: [:create, :destroy]
  end

  post 'password/forgot', {to: 'password#forgot', as: :forgot_password}
  post 'password/reset', {to: 'password#reset', as: :reset_password}
end

app/models/discussion.rb
class Discussion < ApplicationRecord
    belongs_to :project
    belongs_to :user

    has_many :comments, dependent: :destroy

    validates :title, presence: true, uniqueness: true
    validates :description, presence: true

    # before_validation :newer_published_at

    # private

    # def newer_published_at
    #     return unless due_date.present?
    #     self.errors.add(:due_date, "due date comes after created at") unless created_at < Project.due_date
    # end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
    before_action :find_id, except: [:new, :create]
    before_action :authenticate!, except: [:show]
    before_action :authorize, only: [:destroy, :edit, :update]

    def new
        @project = Project.find params[:project_id]
        @discussion = Discussion.new
    end

    def create
        @project = Project.find params[:project_id]
        @discussion = Discussion.new discussion_params
        @discussion.project = @project
        @discussion.user = current_user
        if @discussion.save
            redirect_to project_path(@discussion.project_id)
        else
            # @discussions = @project.discussions.order(created_at: :desc)
            render :new
        end
    end

    def show
        # @discussion = Discussion.find params[:id]
        # @project = Project.find params[:project_id]
        @comment = Comment.new
        @comments = @discussion.comments.order(created_at: :desc)
    end

    def destroy
        # @discussion = Discussion.find params[:id]
        if @discussion.destroy
            redirect_to project_path(@discussion.project_id), notice: "Discussion successfully deleted!"
        else
            redirect_to project_path(@discussion.project_id), alert: "The post could not be deleted"
        end
    end

    def edit
        # @discussion = Discussion.find params[:id]
    end

    def update
        # @discussion = Discussion.find params[:id]
        if @discussion.update discussion_params
            redirect_to project_path(@discussion.project_id), notice: "Discussion updated"
        else
            render :edit, alert: "Unable to update. Try again!"
        end
    end

    private

    def discussion_params
        params.require(:discussion).permit(:title, :description)
    end

    def find_id
        @discussion = Discussion.find params[:id]
    end

    def authorize
        redirect_to root_path, alert: 'Not authorized' unless can?(:crud, @discussion)
    end
end

app/views/discussions/edit.html.erb
<h1>Edit</h1>
<%= form_with model: [@project, @discussion], local: true do |form| %>
    <% if @discussion.errors.any? %>
        <p>Try again!</p>
        <p><%= @discussion.errors.full_messages.join(',')%></p>
    <% end %>
    <div>
        <%= form.label :title%>
        <%= form.text_field :title%>
    </div>
    <div>
        <%= form.label :description%>
        <%= form.text_field :description%>
    </div>
    <%= form.submit%>
<% end %>

app/views/discussions/new.html.erb
<h1>Discussion</h1>
<%= form_with model: [@project, @discussion], local: true do |form| %>
    <% if @discussion.errors.any? %>
        <p>Try again!</p>
        <p><%= @discussion.errors.full_messages.join(',')%></p>
    <% end %>
    <div>
        <%= form.label :title%>
        <%= form.text_field :title%>
    </div>
    <div>
        <%= form.label :description%>
        <%= form.text_field :description%>
    </div>
    <%= form.submit%>
<% end %>

app/views/discussions/show.html.erb
<h1><%=@discussion.title%></h1>
<p><%=@discussion.description%></p>
<small><%= time_ago_in_words(@discussion.updated_at) %></small>
<small><%= link_to "Delete", project_discussion_path(@discussion.project_id, @discussion), method: :delete, data: {confirm: "Are you sure you want to delete your comment?"} %></small>
<small><%= link_to "Edit", edit_project_discussion_path(@discussion.project_id, @discussion) %></small>

<%= form_with model: [@discussion, @comment], local: true do |form| %>
    <div>
        <%= form.label :body%>
        <%= form.text_area :body%>
    </div>
    <%= form.submit %>
<% end %>        

<% @comments.each do |comment| %>
    <p><%= comment.body%></p>
    <small><%= time_ago_in_words(comment.updated_at) %></small>
    <small><%= link_to "Delete", discussion_comment_path(comment.discussion_id, comment), method: :delete, data: {confirm: "Are you sure you want to delete your comment?"} %></small>
    <small><%= link_to "Edit", edit_discussion_comment_path(comment.discussion_id, comment)%></small>
<% end %>        