config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'users/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', {to: 'home#index', as: 'root'}
  get '/about', {to: 'home#about'}
  get '/my_favourites', {to: 'home#favourites', as: 'my_favourites'}

  resources :projects

  resources :projects do
    resources :tasks
    resources :discussions
  end

  resources :discussions do
    resources :comments
  end

  patch '/projects/:project_id/tasks/:id/complete', {to: 'tasks#complete', as: 'task_complete'}

  resources :users, only: [:new, :create, :edit, :update]
  get '/users/:id/edit_password', {to:"users#edit_password", as: :edit_user_password}
  # patch '/users/:id/update_password', {to: 'users#update_password', as: :user_password}
  resource :sessions, only: [:new, :create, :destroy]

  resources :projects do
    resources :favourites, only: [:create, :destroy]
  end

  post 'password/forgot', {to: 'password#forgot', as: :forgot_password}
  post 'password/reset', {to: 'password#reset', as: :reset_password}
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy
    has_many :discussions, dependent: :destroy
    has_many :favourites, dependent: :destroy
    has_many :favourited_users, through: :favourites, source: :user
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    validates :title, presence: true, uniqueness: true
    validates :description, presence: true
    after_save :newer_due_date

    def tag_name
        self.tags.map {|tag| tag.name}.join(',')
    end

    def tag_name=(custom_tag)
        self.tags = custom_tag.strip.split(',').map {|tag| Tag.find_or_initialize_by(name: tag)}
    end

    private

    def newer_due_date
        return unless due_date.present?
        self.errors.add(:due_date, "due date comes after created at") unless due_date > created_at
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :find_id, only: [:show, :destroy, :edit, :update]
    before_action :authenticate!, except: [:show, :index]
    before_action :authorize, only: [:destroy, :edit, :update]

    def new
        @project = Project.new 
    end

    def create
        @project = Project.new project_params
        @project.user = current_user

        if @project.save
            redirect_to project_path(@project), notice: "Saved!"
        else
            flash[:alert] = "error"
            render :new
        end
    end

    def show
        # @project = Project.find params[:id]
        @task = Task.new
        @tasks = @project.tasks.order(created_at: :desc)
        @discussions = @project.discussions.order(created_at: :desc)
    end

    def index
        if params[:tag]
            @tag = Tag.find_or_initialize_by(name: params[:tag])
            @project = @tag.projects.order(created_at: :desc)
        else
            @project = Project.all.order(created_at: :desc)
        end
    end

    def destroy
        # @project = Project.find params[:id]
        @project.destroy
        redirect_to projects_path
    end

    def edit
        # @project = Project.find params[:id]
    end

    def update
        # @project = Project.find params[:id]
        if @project.update project_params
            redirect_to project_path(@project), notice: 'updated!'
        else
            render :edit
        end
    end

    private
    
    def project_params 
        params.require(:project).permit(:title, :description, :due_date, :tag_name)
    end

    def find_id
        @project = Project.find params[:id]
    end

    def authorize
        redirect_to root_path, alert: 'Not authorized' unless can?(:crud, @project)
    end
end

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
    <ul>
        <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %><li>
        <% end %>
    </ul>
<% end %>

<%= form_with model: @project, local:true do |form| %>
    <div>
        <%= form.label :title%>
        <%= form.text_field :title, placeholder: "title" %>
    </div>
    <div>
        <%= form.label :description%>
        <%= form.text_field :description, placeholder:"what is the project about?"%>
    </div>
    <div>
        <%= form.label :due_date%>
        <%= form.text_field :due_date, placeholder: "2019-07-04"%>
    </div>
    <div>
        <%= form.label :tags%>
        <%= form.text_field :tag_name %>
    </div>
    <%= form.submit%>
<% end %>
<script>
    $('#project_tag_name').selectize({
        delimiter: ',',
        persist: false,
        labelField: 'name',
        valueField: 'name',
        searchField: 'name',
        options: <%= Tag.select(:name).to_json(except: [:id]).html_safe%>,
        create: function(input) {
            return {
                name: input
            }
        }
    });
</script>

app/views/projects/edit.html.erb
<h1>Edit your project</h1>

<%= render "form"%>

app/views/projects/index.html.erb
<% @project.each do |project| %>
    <% if params[:tag] %>
        <span>Products with <p class="badge badge-light"><%= params[:tag] %></p></span>
    <%end%>

    <h1><%= link_to project.title, project_path(project.id) %></h1>
    <p><%= project.description %></p>
    <hr>
<% end %>

app/views/projects/new.html.erb
<h1>Create a new a project</h1>

<%= render "form"%>

app/views/projects/show.html.erb
<h1><%= @project.title%></h1>
<p><%= @project.description%></p>
<p>Due: <%= @project.due_date%></p>
<small>Posted by <%= @project.user.full_name%> <%= time_ago_in_words(@project.updated_at)%></small>

<% favourited_user = @project.favourites.find_by(user:current_user) %>
<% if favourited_user.present? %>
    <%= link_to "💔Un-favourite💔", project_favourite_path(@project, favourited_user), method: :delete%>
<% else %>
    <%= link_to "Favourite", project_favourites_path(@project), method: :post%>
<% end %>
<small><%= @project.favourites.count%> favourites </small>
<br/>
<div>Tags: 
    <% @project.tags.each do |tag|%>
        <p class="badge badge-light"><%= link_to tag.name, projects_path(tag: tag.name) %></p> 
    <% end %>
</div>
<br/>
<%= link_to "Delete", project_path(@project.id), method: :delete, data: {confirm: "Are you sure you want to delete the project?"}%>
<%= link_to "Edit", edit_project_path(@project) %>
<br/>
<%= link_to "Post a discussion on this project", new_project_discussion_path(@project.id) %>
<br/>

<h1>Tasks</h1>
<%= form_with model:[@project, @task], local: true do |form| %>
    <% if @task.errors.any? %>
        <p><%= @task.errors.full_messages.join(",")%></p>
    <% end %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>
    <div>
        <%= form.label :due_date %>
        <%= form.text_field :due_date, placeholder: "2019-07-04" %>
    </div>
    <%= form.submit%>
<% end %>

<% @tasks.each do |task| %>
    <p>
        <%= task.title%>
        <%= task.description%>
        Due: <%= task.due_date%>
        <small><%= time_ago_in_words(task.created_at)%></small>
        <% if task.complete == false%>
            <small><%= link_to "Mark Completed", task_complete_path(task.project_id, task.id), method: :patch %></small>
        <% else %>
            <small><%= link_to "Mark Incomplete", task_complete_path(task.project_id, task.id), method: :patch %></small>
        <% end %>
        <small><%= link_to "Delete", project_task_path(@project, task.id), method: :delete, data: {confirm: "Are you sure you want to delete the task"}%></small>
    </p>
<% end %>

<h1>List of Discussions</h1>
<% @discussions.each do |discussion| %>
    <h3><%= discussion.title %></h3>
    <p><%= discussion.description %></p>
    <small><%= time_ago_in_words(discussion.updated_at) %></small> |
    <small><%= link_to "View Details", discussion_path(discussion.id) %></small> 
<% end %>