config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'users/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', {to: 'home#index', as: 'root'}
  get '/about', {to: 'home#about'}
  get '/my_favourites', {to: 'home#favourites', as: 'my_favourites'}

  resources :projects

  resources :projects do
    resources :tasks
    resources :discussions
  end

  resources :discussions do
    resources :comments
  end

  patch '/projects/:project_id/tasks/:id/complete', {to: 'tasks#complete', as: 'task_complete'}

  resources :users, only: [:new, :create, :edit, :update]
  get '/users/:id/edit_password', {to:"users#edit_password", as: :edit_user_password}
  # patch '/users/:id/update_password', {to: 'users#update_password', as: :user_password}
  resource :sessions, only: [:new, :create, :destroy]

  resources :projects do
    resources :favourites, only: [:create, :destroy]
  end

  post 'password/forgot', {to: 'password#forgot', as: :forgot_password}
  post 'password/reset', {to: 'password#reset', as: :reset_password}
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pmtool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <%= link_to "Home", root_path%> | 
  <%= link_to "About", about_path%> | 
  <%= link_to "New Project", new_project_path%> | 
  <%= link_to "List of Projects", projects_path%> |
  
  <% if user_signed_in? %>
    <%= link_to "Sign Out", sessions_path, method: :delete, data: {confirm: "Are you sure you want to log out?"}%> | 
    <%= link_to "Change Password", edit_user_password_path(current_user.id)%> |
    <%= link_to "My Favourites", my_favourites_path%>
    <p>Signed in as <%= link_to current_user.full_name, edit_user_path(current_user.id)%></p>
  <% else %>
    <%= link_to "Sign In", new_sessions_path%> | 
    <%= link_to "Sign Up", new_user_path%> |
  <% end %>

  <%= flash[:notice] || flash[:alert] %>
  <%= yield %>
  </body>
</html>